# Dockerfile
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9
COPY ./src /app/src
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "src.app:create_app", "--host=0.0.0.0", "--port=80"]